version: '3.4'

services:

  rabbitmq-svc:
    # image: rabbitmq:3-management
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "15672:15672"
      - "5672:5672"